# Generated by Django 5.2.9 on 2026-01-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityzone',
            name='average_income_tier',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='air_quality_index',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='HealthStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('respiratory_cases_active', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cityzone')),
            ],
        ),
    ]
