# Generated by Django 5.2.9 on 2026-01-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PLANNER', 'City Planner'), ('AGRICULTURIST', 'Agriculturist'), ('HEALTH', 'Health Official'), ('CITIZEN', 'Citizen')], max_length=20),
        ),
    ]
